---
title: "sophie_report.qmd"
editor: visual
---

```{r}

#| label: load-pkgs
#| message: false

library(tidyverse)
library(tidymodels)
```

```{r}

#| label: load-data-1

march_madness <- read_csv("data/Tournament_Data.csv")

march_madness <- march_madness |>
  filter(round != 0 & round != 68) |>
  mutate(round = as.factor(round))

names(march_madness)

```

```{r}

march_madness |> 
  ggplot(aes(x = round, y = seed)) +
  geom_boxplot()

```

```{r}

march_madness |> 
  ggplot(aes(x = round, y = b_adj_eff)) +
  geom_boxplot()

```

```{r}

march_madness |> 
  ggplot(aes(x = round, y = elite_sos)) +
  geom_boxplot()

```

```{r}

march_madness |> 
  ggplot(aes(x = round, y = wins_above_bubble)) +
  geom_boxplot()

```

```{r}

set.seed(1234) 
march_madness_split <- initial_split(march_madness, prop = 0.80) 
train_data <- training(march_madness_split)
test_data <- testing(march_madness_split) 
```

```{r}

model2 <- logistic_reg() |>
  set_engine("glm") |>
  fit(round ~ b_adj_eff, data = train_data, family = "binomial")

tidy(model2)
```

$\widehat{round}$ = 14.39 - 0.41 \* b_adj_eff

```{r}

cat("model2 AIC:", glance(model2)$AIC)
```
